# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vTsAC0ZupJxUpvPLQQOb_s1NBsQV30E
"""

import tensorflow_hub as hub
import tensorflow_text as text

preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

def func():

import tensorflow_hub as hub
import tensorflow_text as text

preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

# Load the preprocessing model from TensorFlow Hub
bert_preprocess_model = hub.KerasLayer(preprocess_url)

def func():
    text_test = ['Malla Reddy founded the college Malla Reddy', 'nice College indeed','I love python programming']
    text_preprocessed = bert_preprocess_model(text_test)
    text_preprocessed.keys()

import tensorflow_hub as hub
import tensorflow_text as text

preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

# Load the preprocessing model from TensorFlow Hub
bert_preprocess_model = hub.KerasLayer(preprocess_url)

def func():
    text_test = ['Malla Reddy founded the college Malla Reddy', 'nice College indeed','I love python programming']
    text_preprocessed = bert_preprocess_model(text_test)
    return text_preprocessed # Return the preprocessed text

# Call the function to get the preprocessed data
text_preprocessed = func()

# Now you can access text_preprocessed
text_preprocessed['input_mask']

text_preprocessed['input_word_ids']

bert_model = hub.KerasLayer(encoder_url)

bert_results = bert_model(text_preprocessed)

bert_results.keys()

bert_results['pooled_output']

bert_results['encoder_outputs']

bert_results['sequence_output']



